version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.war
  discard-paths: yes